# Generated by Django 4.0.5 on 2022-09-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='Total_Stock',
            field=models.IntegerField(default=''),
        ),
    ]
