# Generated by Django 4.0.5 on 2022-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subproduct_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='Total_Stock',
            field=models.IntegerField(),
        ),
    ]
